# This is our workflow - publish-image.yaml
name: Run event-catalogue image on GitHub Actions Hosted Runner

on:
  workflow_dispatch:

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t jsdads11/docker-git-hub-bash-hello-world
      - name: run
        run: |
          docker run -t jsdads11/docker-git-hub-bash-hello-world
